# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 1000  # Hz

    dual_panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_panda_hand_controller:
      type: position_controllers/GripperActionController


    right_panda_hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

dual_panda_arm_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - left_panda_joint1
      - left_panda_joint2
      - left_panda_joint3
      - left_panda_joint4
      - left_panda_joint5
      - left_panda_joint6
      - left_panda_joint7
      - right_panda_joint1
      - right_panda_joint2
      - right_panda_joint3
      - right_panda_joint4
      - right_panda_joint5
      - right_panda_joint6
      - right_panda_joint7
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 200.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0 

left_panda_hand_controller:
  ros__parameters:
    use_sim_time: true
    joint: left_panda_finger_joint1
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
right_panda_hand_controller:
  ros__parameters:
    use_sim_time: true
    joint: right_panda_finger_joint1
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0